<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>True</UseWindowsForms>
    <UseWPF>True</UseWPF>
    <ApplicationIcon>Titlecard_S1E6_thejiggler(2).ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Titlecard_S1E6_thejiggler(2).ico" />
  </ItemGroup>

</Project>
